
-- Run this in your Supabase SQL Editor

ALTER TABLE packets 
ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS in_transit BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS sensor_data TEXT,
ADD COLUMN IF NOT EXISTS battery_status TEXT,
ADD COLUMN IF NOT EXISTS firmware_version TEXT,
ADD COLUMN IF NOT EXISTS from_location TEXT,
ADD COLUMN IF NOT EXISTS to_location TEXT,
ADD COLUMN IF NOT EXISTS packet_type TEXT,
ADD COLUMN IF NOT EXISTS auth_type TEXT,
ADD COLUMN IF NOT EXISTS user_details TEXT;
